# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: isntall uv and Set up Python 3.10
      uses: astral-sh/setup-uv@v1
      with:
        python-version: "3.10"
        cache-dependency-path: 'uv.lock'
    
    - name: Install dependencies
      run: uv sync
    - name: Generate files
      run: uv run main.py
    - name: upload files
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output/*.json
